import { RoomInput, EstimateAssumptions } from "../types/estimate";

export const DEFAULT_ASSUMPTIONS: EstimateAssumptions = {
  coverageRateM2PerLitre: 14,
  wallLabourProductivityM2PerHour: 10,
  ceilingLabourProductivityM2PerHour: 7,
  labourHourlyRateAud: 65,
  paintPricesAudPerLitre: {
    budget: 18,
    standard: 28,
    premium: 40,
  },
  commonTinSizesLitre: [15, 10, 4, 2, 1],
};

export const DEFAULT_ROOMS: RoomInput[] = [
  {
    id: "living",
    name: "Living",
    length: 5.2,
    width: 4.1,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    length: 3.4,
    width: 3.1,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
  {
    id: "bedroom-1",
    name: "Bedroom 1",
    length: 4.0,
    width: 3.6,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
  {
    id: "hall",
    name: "Hall",
    length: 5.5,
    width: 1.1,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
  {
    id: "bedroom-2",
    name: "Bedroom 2",
    length: 3.4,
    width: 3.2,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
  {
    id: "bath",
    name: "Bath",
    length: 2.4,
    width: 2.1,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
  {
    id: "laundry",
    name: "Laundry",
    length: 2.2,
    width: 1.8,
    ceilingHeight: 2.4,
    paintWalls: true,
    paintCeilings: true,
    coats: 2,
    paintQuality: "standard",
  },
];
