import React from "react";
import type { RoomInput, ProjectEstimate } from "@/types/estimate";
import {
  formatCurrency,
  formatArea,
  formatHours,
  formatTinRecommendation,
} from "@/lib/formatting";

interface PrintEstimateProps {
  rooms: RoomInput[];
  projectEstimate: ProjectEstimate;
}

export const PrintEstimate: React.FC<PrintEstimateProps> = ({
  rooms,
  projectEstimate,
}) => {
  return (
    <div className="hidden print:flex flex-col gap-6 w-full text-stone-900 bg-white p-4">
      <div className="flex justify-between items-start border-b border-stone-300 pb-4">
        <div>
          <h1 className="text-2xl font-bold uppercase tracking-tight text-stone-900">
            Paint Estimate Quote
          </h1>
          <p className="text-xs text-stone-500 mt-1">
            Generated by Pigmenta Paint Calculator
          </p>
        </div>
        <div className="text-right">
          <span className="text-[10px] text-stone-400 uppercase font-bold tracking-wider">Date</span>
          <span className="block text-sm font-semibold text-stone-850 mt-0.5">
            {new Date().toLocaleDateString("en-AU")}
          </span>
        </div>
      </div>

      {/* Rooms Summary Table */}
      <div>
        <h2 className="text-sm font-bold uppercase tracking-wider text-stone-500 mb-2.5">
          Room Specifications
        </h2>
        {rooms.length === 0 ? (
          <p className="text-xs text-stone-400 italic">No rooms configured in this estimate.</p>
        ) : (
          <table className="w-full border-collapse text-xs text-left">
            <thead>
              <tr className="border-b-2 border-stone-350 font-bold text-stone-600 bg-stone-50/50">
                <th className="py-2 pr-2">Room</th>
                <th className="py-2 text-right">Dimensions (m)</th>
                <th className="py-2 text-center">Coats</th>
                <th className="py-2 text-center">Quality</th>
                <th className="py-2 text-right">Surface Area</th>
                <th className="py-2 text-right">Est. Cost</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-200">
              {projectEstimate.rooms.map((est, i) => {
                const room = rooms[i];
                if (!room) return null;
                return (
                  <tr key={room.id} className="align-middle">
                    <td className="py-2.5 font-semibold text-stone-900">{room.name || `Room ${i + 1}`}</td>
                    <td className="py-2.5 text-right font-mono">
                      {room.length.toFixed(1)}L × {room.width.toFixed(1)}W × {room.ceilingHeight.toFixed(1)}H
                    </td>
                    <td className="py-2.5 text-center">{room.coats}</td>
                    <td className="py-2.5 text-center capitalize">{room.paintQuality}</td>
                    <td className="py-2.5 text-right font-mono">
                      {formatArea(est.paintableWallAreaM2 + est.paintableCeilingAreaM2)}
                    </td>
                    <td className="py-2.5 text-right font-mono font-bold text-stone-900">
                      {formatCurrency(est.totalCostAud)}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>

      {/* Project Cost & Materials Summary */}
      <div className="grid grid-cols-2 gap-8 border-t border-stone-300 pt-6 mt-4">
        <div className="flex flex-col gap-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Paint Materials Estimate
          </h3>
          <div className="text-xs space-y-1.5 text-stone-600">
            <div className="flex justify-between">
              <span>Wall Paint Recommendation:</span>
              <span className="font-semibold text-stone-850">{formatTinRecommendation(projectEstimate.totalWallTins)}</span>
            </div>
            <div className="flex justify-between">
              <span>Ceiling Paint Recommendation:</span>
              <span className="font-semibold text-stone-850">{formatTinRecommendation(projectEstimate.totalCeilingTins)}</span>
            </div>
            <div className="flex justify-between">
              <span>Total Materials Cost:</span>
              <span className="font-semibold text-stone-850">{formatCurrency(projectEstimate.totalPaintCostAud)}</span>
            </div>
          </div>
        </div>

        <div className="flex flex-col gap-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Labour Estimate
          </h3>
          <div className="text-xs space-y-1.5 text-stone-600">
            <div className="flex justify-between">
              <span>Total Labour Hours:</span>
              <span className="font-semibold text-stone-850">{formatHours(projectEstimate.totalLabourHours)}</span>
            </div>
            <div className="flex justify-between">
              <span>Total Labour Cost:</span>
              <span className="font-semibold text-stone-850">{formatCurrency(projectEstimate.totalLabourCostAud)}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Final Price Block */}
      <div className="border-t-2 border-stone-900 pt-4 mt-6 flex justify-between items-center bg-stone-50 p-4 rounded-xl">
        <div>
          <span className="text-[10px] text-stone-400 uppercase font-bold tracking-wider">Project Grand Total</span>
          <span className="block text-2xl font-black text-stone-900 mt-0.5">
            {formatCurrency(projectEstimate.totalProjectCostAud)}
          </span>
        </div>
        <div className="text-right text-[10px] text-stone-400 font-medium">
          * All estimates exclude GST and feature trade-optimized parameters.
        </div>
      </div>
    </div>
  );
};
